services:
  postgres:
    image: "postgres:18-alpine"
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_DB=home_energy_tracker
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      - db-data:/var/lib/postgresql
      - db-logs:/var/log/postgresql

  kafka:
    image: apache/kafka:latest
    container_name: kafka
    restart: always
    environment:
      - KAFKA_NODE_ID=1
      - KAFKA_CLUSTER_ID=energy-tracker-cluster-1
      - KAFKA_PROCESS_ROLES=broker,controller
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092,EXTERNAL://0.0.0.0:9094,CONTROLLER://0.0.0.0:9093
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=1
      - KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS=0
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_NUM_PARTITIONS=1
    ports:
      - "9092:9092"
      - "9094:9094"
    volumes:
      - ./docker/kafka_data:/var/lib/kafka/data

  kafka-ui:
    image: ghcr.io/kafbat/kafka-ui:latest
    container_name: kafka-ui
    restart: unless-stopped
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
      - DYNAMIC_CONFIG_ENABLED=true
    ports:
      - "8070:8080"
    depends_on:
      - kafka

  influxdb:
    image: influxdb:2.8
    container_name: influxdb
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=admin123
      - DOCKER_INFLUXDB_INIT_ORG=yurupari
      - DOCKER_INFLUXDB_INIT_BUCKET=usage-bucket
      - DOCKER_INFLUXDB_INIT_RETENTION=1w
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=yurupari-token-db
    ports:
      - "8072:8086"
    volumes:
      - ./influxdb_data:/var/lib/influxdb2

  user-service:
    build:
      context: .
      dockerfile: ./user-service/src/main/docker/Dockerfile
    container_name: user-service
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=home_energy_tracker
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=none
    volumes:
      - ./logs/:/logs
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  device-service:
    build:
      context: .
      dockerfile: ./device-service/src/main/docker/Dockerfile
    container_name: device-service
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=home_energy_tracker
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=none
    volumes:
      - ./logs/:/logs
    ports:
      - "8081:8081"
    depends_on:
      - postgres

  ingestion-service:
    build:
      context: .
      dockerfile: ./ingestion-service/src/main/docker/Dockerfile
    container_name: ingestion_service
    environment:
      - KAFKA_SERVER=kafka
      - KAFKA_EXTERNAL_PORT=9092
    volumes:
      - ./logs/:/logs
    ports:
      - "8082:8082"
    depends_on:
      - kafka

  usage-service:
    build:
      context: .
      dockerfile: ./usage-service/src/main/docker/Dockerfile
    container_name: usage_service
    environment:
      - KAFKA_SERVER=kafka
      - KAFKA_EXTERNAL_PORT=9092
      - INFLUX_HOST=http://influxdb:8086
      - INFLUXDB_TOKEN=yurupari-token-db
      - INFLUXDB_ORG=yurupari
      - INFLUXDB_BUCKET=usage-bucket
      - DEVICE_SERVICE_URL=http://device-service:8081
      - USER_SERVICE_URL=http://user-service:8080
    volumes:
      - ./logs/:/logs
    ports:
      - "8083:8083"
    depends_on:
      - kafka
      - influxdb
      - user-service
      - device-service

  alert-service:
    build:
      context: .
      dockerfile: ./alert-service/src/main/docker/Dockerfile
    container_name: alert_service
    environment:
      - KAFKA_SERVER=kafka
      - KAFKA_EXTERNAL_PORT=9092
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=home_energy_tracker
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=none
    volumes:
      - ./logs/:/logs
    ports:
      - "8084:8084"
    depends_on:
      - kafka
      - postgres
      - user-service

volumes:
  db-data:
  db-logs:
  kafka-data:
