server:
  port: 9000

spring:
  application:
    name: api-gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${ISSUER_URI}

services:
  items:
    user-service:
      url: ${USER_SERVICE_URL}
      path: /api/v1/user/**
      circuitBreakerId: userServiceCircuitBreaker
      fallbackPath: /fallback/user
      fallbackMessage: User service is down
      apiDocsPath: /docs/user-service/v3/api-docs
    device-service:
      url: ${DEVICE_SERVICE_URL}
      path: /api/v1/device/**
      circuitBreakerId: deviceServiceCircuitBreaker
      fallbackPath: /fallback/device
      fallbackMessage: Device service is down
      apiDocsPath: /docs/device-service/v3/api-docs
    ingestion-service:
      url: ${INGESTION_SERVICE_URL}
      path: /api/v1/ingestion/**
      circuitBreakerId: ingestionServiceCircuitBreaker
      fallbackPath: /fallback/ingestion
      fallbackMessage: Ingestion service is down
      apiDocsPath: /docs/ingestion-service/v3/api-docs
    insight-service:
      url: ${INSIGHT_SERVICE_URL}
      path: /api/v1/insight/**
      circuitBreakerId: insightServiceCircuitBreaker
      fallbackPath: /fallback/insight
      fallbackMessage: Insight service is down
      apiDocsPath: /docs/insight-service/v3/api-docs

management:
  health:
    circuitbreakers:
      enabled: true
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info,metrics,circuitbreakers

resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 8
        failureRateThreshold: 20
        minimum-number-of-calls: 4
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 2
        automaticTransitionFromOpenToHalfOpenEnabled: true
  timelimiter:
    configs:
      default:
        timeoutDuration: 5s

keycloak:
  auth:
    jwt-set-uri: ${JWT_SET_URI}

security:
  excluded:
    urls: /actuator/**,/swagger-ui.html,/swagger-ui/**,/docs/**,/v3/api-docs/**,/swagger-resources/**,/api-docs/**

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: User Service
        url: /docs/user-service/v3/api-docs
      - name: Device Service
        url: /docs/device-service/v3/api-docs
      - name: Ingestion Service
        url: /docs/ingestion-service/v3/api-docs
      - name: Insight Service
        url: /docs/insight-service/v3/api-docs
  api-docs:
    path: /v3/api-docs
