server:
  port: 9000

spring:
  application:
    name: api-gateway

services:
  items:
    user-service:
      url: http://localhost:8080
      path: /api/v1/user/**
    device-service:
      url: http://localhost:8081
      path: /api/v1/device/**
    ingestion-service:
      url: http://localhost:8082
      path: /api/v1/ingestion/**
    insight-service:
      url: http://localhost:8085
      path: /api/v1/insight/**
