server:
  port: 8084

spring:
  application:
    name: alert-service

  kafka:
    bootstrap-servers: ${KAFKA_SERVER}:${KAFKA_EXTERNAL_PORT}
    consumer:
      group-id: alert-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.type.mapping: alertingEvent:com.yurupari.common_data.kafka.event.AlertingEvent
        spring.json.trusted.packages: com.yurupari.*

  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false

email:
  from: noreply@yurupari.com

services:
  user-service:
    url: ${USER_SERVICE_URL}

feign:
  circuitbreaker:
    enabled: true

resilience4j:
  retry:
    instances:
      user-service:
        max-attempts: 3
        wait-duration: 100ms
        enable-exponential-backoff: true
        exponential-backoff-multiplier: 2
        retry-exceptions:
          - feign.FeignException.InternalServerError
          - java.io.IOException
          - feign.FeignException.GatewayTimeout
      device-service:
        max-attempts: 3
        wait-duration: 100ms
        enable-exponential-backoff: true
        exponential-backoff-multiplier: 2
        retry-exceptions:
          - feign.FeignException.InternalServerError
          - java.io.IOException
          - feign.FeignException.GatewayTimeout

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: when_authorized
  metrics:
    tags:
      application: ${spring.application.name}
