server:
  port: 8085

spring:
  application:
    name: insight-service

services:
  usage-service:
    url: ${USAGE_SERVICE_URL}
  user-service:
    url: ${USER_SERVICE_URL}

feign:
  circuitbreaker:
    enabled: true

resilience4j:
  retry:
    instances:
      user-service:
        max-attempts: 3
        wait-duration: 100ms
        enable-exponential-backoff: true
        exponential-backoff-multiplier: 2
        retry-exceptions:
          - feign.FeignException.InternalServerError
          - java.io.IOException
          - feign.FeignException.GatewayTimeout
      device-service:
        max-attempts: 3
        wait-duration: 100ms
        enable-exponential-backoff: true
        exponential-backoff-multiplier: 2
        retry-exceptions:
          - feign.FeignException.InternalServerError
          - java.io.IOException
          - feign.FeignException.GatewayTimeout
