server:
  port: 8085

spring:
  application:
    name: insight-service
  ai:
    ollama:
      base-url: ${OLLAMA_URL}
      chat.options.model: deepseek-coder
      init.pull-model-strategy: never

services:
  usage-service:
    url: ${USAGE_SERVICE_URL}
  user-service:
    url: ${USER_SERVICE_URL}

feign:
  circuitbreaker:
    enabled: true

resilience4j:
  retry:
    instances:
      user-service:
        max-attempts: 3
        wait-duration: 100ms
        enable-exponential-backoff: true
        exponential-backoff-multiplier: 2
        retry-exceptions:
          - feign.FeignException.InternalServerError
          - java.io.IOException
          - feign.FeignException.GatewayTimeout
      device-service:
        max-attempts: 3
        wait-duration: 100ms
        enable-exponential-backoff: true
        exponential-backoff-multiplier: 2
        retry-exceptions:
          - feign.FeignException.InternalServerError
          - java.io.IOException
          - feign.FeignException.GatewayTimeout

prompts:
  base-path: /templates/prompts/
  files:
    saving-tips: saving-tips.txt
    overview: overview.txt

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: when_authorized
  metrics:
    tags:
      application: ${spring.application.name}

documentation:
  contact:
    url: https://github.com/yurupari
  license:
    name: Creative Commons Attribution-NonCommercial 4.0 International License
    url: https://creativecommons.org/licenses/by-nc/4.0/
  title: Insight Service API
  description: Insight Service API for Home Energy Tracker Project
  version: @version@
